
Developer Guide
---------------
This part of the guide focuses on feature allocation for specific maintenance tasks. 

.. toctree::
    :maxdepth: 2

    guide/sendMail

    

Design Note
-----------
.. toctree::
    :maxdepth: 2

    design/sendMail



API Reference
-------------
This part of the documentation dedicates to prople who are looking for information on a specific function, class or method.

.. toctree::
    :maxdepth: 3

    api/sendMail


Change Log
---------------
This part of daily changelog. 

.. toctree::
    :maxdepth: 2

    changeLog
    changeLogExample



File List
----------

  ..toctree::
    :maxdepth: 1

    files/messages_en_CN.properties
