
Developer Guide
---------------
This part of the guide focuses on feature allocation for specific maintenance tasks. 

.. toctree::
    :maxdepth: 2

    guide/sendMail

    

Design Note
-----------
.. toctree::
    :maxdepth: 2

    design/sendMail



API Reference
-------------
This part of the documentation dedicates to prople who are looking for information on a specific function, class or method.

.. toctree::
    :maxdepth: 3

    api/sendMail


Additional Note
---------------
This part of note declares the license of doc Document. 

.. toctree::
    :maxdepth: 2

    license
